# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: csv_lazy 0.0.10 ruby lib

Gem::Specification.new do |s|
  s.name = "csv_lazy".freeze
  s.version = "0.0.10"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Kasper Johansen".freeze]
  s.date = "2018-01-24"
  s.description = "A small CSV lib that skips whitespace-format-bugs and more.".freeze
  s.email = "k@spernj.org".freeze
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "csv_lazy.gemspec",
    "lib/csv_lazy.rb",
    "peak_flow.yml",
    "spec/csv_lazy_spec.rb",
    "spec/spec_helper.rb",
    "spec/test1.csv.gz",
    "spec/test2.csv"
  ]
  s.homepage = "http://github.com/kaspernj/csv_lazy".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "2.6.11".freeze
  s.summary = "A small CSV lib that skips whitespace-format-bugs and more.".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<string-strtr>.freeze, [">= 0"])
      s.add_development_dependency(%q<bundler>.freeze, [">= 1.0.0"])
      s.add_development_dependency(%q<jeweler>.freeze, ["= 2.3.9"])
      s.add_development_dependency(%q<rspec>.freeze, ["= 3.7.0"])
    else
      s.add_dependency(%q<string-strtr>.freeze, [">= 0"])
      s.add_dependency(%q<bundler>.freeze, [">= 1.0.0"])
      s.add_dependency(%q<jeweler>.freeze, ["= 2.3.9"])
      s.add_dependency(%q<rspec>.freeze, ["= 3.7.0"])
    end
  else
    s.add_dependency(%q<string-strtr>.freeze, [">= 0"])
    s.add_dependency(%q<bundler>.freeze, [">= 1.0.0"])
    s.add_dependency(%q<jeweler>.freeze, ["= 2.3.9"])
    s.add_dependency(%q<rspec>.freeze, ["= 3.7.0"])
  end
end

